// Datas comemorativas que não são sobre animais, cada uma associada a um animal (ver revisao/datas-associacoes.pdf).
// Gerado a partir das sugestões aprovadas; os táxons foram resolvidos no iNaturalist pelo nome científico.

import type { SpecialDay } from './specialDays'

export const ASSOCIATED_DAYS: SpecialDay[] = [
  { name: 'Dia Mundial da Paz / Confraternização Universal', group: 'Pomba', emoji: '🐦', taxonId: 3017, reason: 'A pomba branca é o símbolo universal da paz.', month: 1, day: 1 },
  { name: 'Dia Mundial do Braile', group: 'Toupeira-nariz-de-estrela', emoji: '🐾', taxonId: 47056, reason: '"Enxerga" pelo tato: o focinho tem o órgão tátil mais sensível entre os mamíferos.', month: 1, day: 4 },
  { name: 'Dia de Reis', group: 'Dromedário', emoji: '🐾', taxonId: 81542, reason: 'Montaria dos Reis Magos na tradição.', month: 1, day: 6 },
  { name: 'Dia do Leitor', group: 'Traça-dos-livros', emoji: '🐞', taxonId: 1445691, reason: 'A "devoradora de livros" original.', month: 1, day: 7 },
  { name: 'Dia do Fotógrafo / da Fotografia', group: 'Tamarutaca (camarão-louva-a-deus)', emoji: '🌊', taxonId: 49796, reason: 'Tem os olhos mais complexos do reino animal.', month: 1, day: 8 },
  { name: 'Dia do Astronauta', group: 'Tardígrado', emoji: '🌊', taxonId: 124337, reason: 'Sobreviveu à exposição direta ao vácuo do espaço.', month: 1, day: 9 },
  { name: 'Dia do Cabeleireiro', group: 'Sagui-cabeça-de-algodão', emoji: '🐾', taxonId: 43391, reason: 'Dono de um dos "penteados" mais famosos da natureza.', month: 1, day: 19 },
  { name: 'Dia do Farmacêutico', group: 'Jararaca', emoji: '🦎', taxonId: 539050, reason: 'O captopril, remédio para pressão, nasceu do estudo do seu veneno.', month: 1, day: 20 },
  { name: 'Dia do Carteiro', group: 'Pombo-correio', emoji: '🐦', taxonId: 3017, reason: 'Entregou mensagens por séculos.', month: 1, day: 25 },
  { name: 'Dia Mundial dos Corais da Amazônia', group: 'Corais', emoji: '🌊', taxonId: 47533, reason: 'A data é sobre o recife da foz do Amazonas.', month: 1, day: 28 },
  { name: 'Dia do Mágico', group: 'Coelho', emoji: '🐾', taxonId: 43151, reason: 'O coelho que sai da cartola.', month: 1, day: 31 },
  { name: 'Dia Mundial das Zonas Úmidas', group: 'Tuiuiú', emoji: '🐦', taxonId: 4773, reason: 'Ave-símbolo do Pantanal, a maior planície alagável do planeta.', month: 2, day: 2 },
  { name: 'Dia do Datiloscopista', group: 'Coala', emoji: '🐾', taxonId: 42983, reason: 'Tem impressões digitais quase idênticas às humanas.', month: 2, day: 5 },
  { name: 'Dia de São Valentim', group: 'Inseparáveis (agapórnis)', emoji: '🐦', taxonId: 19070, reason: 'Os "lovebirds": casais que vivem grudados.', month: 2, day: 14 },
  { name: 'Dia Internacional da Língua Materna', group: 'Tico-tico', emoji: '🐦', taxonId: 9183, reason: 'O canto tem "dialetos" regionais, aprendidos dos adultos.', month: 2, day: 21 },
  { name: 'Dia do Turismo Ecológico', group: 'Arara-azul-grande', emoji: '🐦', taxonId: 18938, reason: 'Estrela do ecoturismo no Pantanal.', month: 3, day: 1 },
  { name: 'Dia Mundial das Pradarias Marinhas', group: 'Tartaruga-verde', emoji: '🦎', taxonId: 39659, reason: 'Pasta nas pradarias de capim-marinho.', month: 3, day: 1 },
  { name: 'Dia do Paleontólogo', group: 'Seriema', emoji: '🐦', taxonId: 14, reason: 'Parente viva mais próxima das extintas "aves do terror".', month: 3, day: 7 },
  { name: 'Dia dos Carecas', group: 'Uacari-branco', emoji: '🐾', taxonId: 43654, reason: 'Macaco amazônico de cabeça pelada; até o nome científico diz "calvus".', month: 3, day: 14 },
  { name: 'Dia Nacional da Conscientização sobre as Mudanças Climáticas', group: 'Pinguim-de-adélia', emoji: '🐦', taxonId: 3810, reason: 'Suas colônias são um termômetro do aquecimento na Antártida.', month: 3, day: 16 },
  { name: 'Dia de São Patrício', group: 'Serpentes', emoji: '🦎', taxonId: 85553, reason: 'Diz a lenda que o santo expulsou as cobras da Irlanda.', month: 3, day: 17 },
  { name: 'Dia do Carpinteiro e do Marceneiro', group: 'Pica-pau-do-campo', emoji: '🐦', taxonId: 18262, reason: 'O carpinteiro das aves.', month: 3, day: 19 },
  { name: 'Dia Nacional do Artesão', group: 'Japu', emoji: '🐦', taxonId: 10126, reason: 'Tece ninhos em forma de bolsa, pendurados nas árvores.', month: 3, day: 19 },
  { name: 'Início do Outono', group: 'Príncipe', emoji: '🐦', taxonId: 16447, reason: 'Migra do sul e chega ao Brasil central no outono.', month: 3, day: 20 },
  { name: 'Dia Internacional da Felicidade', group: 'Quokka', emoji: '🐾', taxonId: 42955, reason: 'O "animal mais feliz do mundo", pelo sorriso permanente.', month: 3, day: 20 },
  { name: 'Dia da Língua Francesa', group: 'Galo', emoji: '🐦', taxonId: 882, reason: 'O galo é o símbolo da França.', month: 3, day: 20 },
  { name: 'Dia Internacional das Florestas', group: 'Harpia (gavião-real)', emoji: '🐦', taxonId: 5321, reason: 'Uma das maiores águias do mundo, moradora das florestas tropicais.', month: 3, day: 21 },
  { name: 'Dia Mundial da Poesia', group: 'Sabiá-laranjeira', emoji: '🐦', taxonId: 12738, reason: '"Minha terra tem palmeiras, onde canta o sabiá."', month: 3, day: 21 },
  { name: 'Dia Mundial das Geleiras', group: 'Pinguim-imperador', emoji: '🐦', taxonId: 3820, reason: 'Depende do gelo antártico para se reproduzir.', month: 3, day: 21 },
  { name: 'Dia Mundial da Água', group: 'Lontra-neotropical', emoji: '🐾', taxonId: 41778, reason: 'Sua presença indica rios saudáveis.', month: 3, day: 22 },
  { name: 'Dia Mundial da Meteorologia', group: 'Pererecas', emoji: '🐸', taxonId: 1658175, reason: 'Coaxam mais quando a umidade sobe, antes da chuva.', month: 3, day: 23 },
  { name: 'Dia Mundial do Teatro', group: 'Ave-lira', emoji: '🐦', taxonId: 12700, reason: 'Imita com perfeição outros animais e até sons humanos.', month: 3, day: 27 },
  { name: 'Dia Internacional do Lixo Zero', group: 'Mosca-soldado-negra', emoji: '🐞', taxonId: 82177, reason: 'Suas larvas transformam restos orgânicos em adubo e ração.', month: 3, day: 30 },
  { name: 'Páscoa', group: 'Tapiti', emoji: '🐾', taxonId: 1649643, reason: 'O coelho nativo do Brasil.', easter: true },
  { name: 'Dia da Mentira', group: 'Polvo-mímico', emoji: '🐚', taxonId: 319764, reason: 'Finge ser outros animais para enganar predadores.', month: 4, day: 1 },
  { name: 'Dia Internacional do Livro Infantil', group: 'Cisne', emoji: '🐦', taxonId: 6921, reason: 'A data é o aniversário de Andersen, autor de "O Patinho Feio".', month: 4, day: 2 },
  { name: 'Dia Mundial da Astronomia', group: 'Besouro rola-bosta', emoji: '🐞', taxonId: 125819, reason: 'Orienta-se à noite pela luz da Via Láctea.', month: 4, day: 8 },
  { name: 'Dia do Unicórnio', group: 'Narval', emoji: '🐾', taxonId: 41459, reason: 'O "unicórnio do mar"; sua presa alimentou a lenda.', month: 4, day: 9 },
  { name: 'Dia Internacional do Voo Espacial Tripulado', group: 'Cão', emoji: '🐾', taxonId: 47144, reason: 'A cadela Laika foi o primeiro animal a orbitar a Terra.', month: 4, day: 12 },
  { name: 'Dia do Humorista', group: 'Hiena-malhada', emoji: '🐾', taxonId: 41886, reason: 'Famosa pela "risada".', month: 4, day: 12 },
  { name: 'Dia do Engenheiro Naval', group: 'Náutilo', emoji: '🐚', taxonId: 123387, reason: 'Controla a flutuação com câmaras de gás, como um submarino.', month: 4, day: 12 },
  { name: 'Dia Nacional da Conservação do Solo', group: 'Minhoca', emoji: '🌊', taxonId: 333586, reason: 'Areja e aduba o solo.', month: 4, day: 15 },
  { name: 'Dia Nacional de Botânica', group: 'Beija-flores', emoji: '🐦', taxonId: 5562, reason: 'Polinizadores de centenas de plantas brasileiras.', month: 4, day: 17 },
  { name: 'Dia Nacional do Livro Infantil', group: 'Rinoceronte', emoji: '🐾', taxonId: 43341, reason: 'Quindim, o rinoceronte do Sítio do Picapau Amarelo (a data é o aniversário de Monteiro Lobato).', month: 4, day: 18 },
  { name: 'Dia da Língua Chinesa', group: 'Panda-gigante', emoji: '🐾', taxonId: 41659, reason: 'Símbolo nacional da China.', month: 4, day: 20 },
  { name: 'Dia Mundial da Criatividade e Inovação', group: 'Corvo-da-nova-caledônia', emoji: '🐦', taxonId: 8032, reason: 'Fabrica as próprias ferramentas.', month: 4, day: 21 },
  { name: 'Dia do Têxtil', group: 'Aranha-de-teia-dourada', emoji: '🕷️', taxonId: 904336, reason: 'Produz uma das sedas mais resistentes conhecidas.', month: 4, day: 21 },
  { name: 'Dia do Planeta Terra', group: 'Baleia-azul', emoji: '🐾', taxonId: 41553, reason: 'O maior animal que já viveu no planeta.', month: 4, day: 22 },
  { name: 'Dia do Descobrimento do Brasil', group: 'Papagaio-verdadeiro', emoji: '🐦', taxonId: 18978, reason: 'Nos primeiros mapas o Brasil era a "Terra dos Papagaios".', month: 4, day: 22 },
  { name: 'Dia de São Jorge', group: 'Dragão-de-komodo', emoji: '🦎', taxonId: 39449, reason: 'O "dragão" de verdade.', month: 4, day: 23 },
  { name: 'Dia do Escoteiro', group: 'Lobo', emoji: '🐾', taxonId: 42048, reason: 'Os escoteiros mais novos são os "lobinhos".', month: 4, day: 23 },
  { name: 'Dia da Língua Inglesa', group: 'Pisco-de-peito-ruivo', emoji: '🐦', taxonId: 13094, reason: 'Ave nacional (por voto popular) do Reino Unido.', month: 4, day: 23 },
  { name: 'Dia da Língua Espanhola', group: 'Lince-ibérico', emoji: '🐾', taxonId: 41975, reason: 'Felino símbolo da fauna da Espanha.', month: 4, day: 23 },
  { name: 'Dia Mundial da Luta Contra a Malária', group: 'Mosquito-prego', emoji: '🐞', taxonId: 146949, reason: 'É o transmissor da malária.', month: 4, day: 25 },
  { name: 'Dia do Goleiro', group: 'Aranhas', emoji: '🕷️', taxonId: 47118, reason: 'Apelido clássico de goleiros, do "Aranha Negra" Yashin em diante.', month: 4, day: 26 },
  { name: 'Dia Internacional em Memória do Desastre de Chernobyl', group: 'Cavalo-de-przewalski', emoji: '🐾', taxonId: 62628, reason: 'Hoje vive solto na zona de exclusão.', month: 4, day: 26 },
  { name: 'Dia Nacional da Caatinga', group: 'Tatu-bola', emoji: '🐾', taxonId: 47080, reason: 'Endêmico do Brasil e símbolo da Caatinga.', month: 4, day: 28 },
  { name: 'Dia Internacional da Dança', group: 'Tangará-dançarino', emoji: '🐦', taxonId: 14306, reason: 'Os machos dançam em grupo para as fêmeas.', month: 4, day: 29 },
  { name: 'Dia do Trabalhador', group: 'Saúva', emoji: '🐞', taxonId: 61284, reason: 'As operárias que nunca param.', month: 5, day: 1 },
  { name: 'Dia do Solo', group: 'Tatu-galinha', emoji: '🐾', taxonId: 47075, reason: 'Escavador que revolve e areja a terra.', month: 5, day: 3 },
  { name: 'Dia do Sertanejo', group: 'Carcará', emoji: '🐦', taxonId: 4715, reason: 'Ave-símbolo do sertão ("pega, mata e come").', month: 5, day: 3 },
  { name: 'Dia de Star Wars', group: 'Papagaio-do-mar', emoji: '🐦', taxonId: 4504, reason: 'Inspirou os porgs: havia tantos na ilha das filmagens que viraram personagem.', month: 5, day: 4 },
  { name: 'Dia Mundial da Língua Portuguesa', group: 'Andorinha-das-chaminés', emoji: '🐦', taxonId: 11901, reason: 'As andorinhas de cerâmica são um ícone de Portugal.', month: 5, day: 5 },
  { name: 'Dia do Campo', group: 'Quero-quero', emoji: '🐦', taxonId: 4867, reason: 'A sentinela dos campos brasileiros.', month: 5, day: 5 },
  { name: 'Dia Nacional da Matemática', group: 'Cigarras periódicas', emoji: '🐞', taxonId: 83854, reason: 'Emergem em ciclos de 13 ou 17 anos, números primos.', month: 5, day: 6 },
  { name: 'Dia do Cartógrafo', group: 'Trinta-réis-ártico', emoji: '🐦', taxonId: 4449, reason: 'Faz a maior migração do planeta, de polo a polo.', month: 5, day: 6 },
  { name: 'Dia Mundial do Silêncio', group: 'Suindara', emoji: '🐦', taxonId: 1578502, reason: 'Voa sem fazer ruído.', month: 5, day: 7 },
  { name: 'Dia do Guia de Turismo', group: 'Indicador-grande', emoji: '🐦', taxonId: 17570, reason: 'Guia pessoas até as colmeias para dividir o mel.', month: 5, day: 10 },
  { name: 'Dia Internacional da Argânia', group: 'Cabra', emoji: '🐾', taxonId: 123070, reason: 'No Marrocos, sobem nas árvores de argânia para comer os frutos.', month: 5, day: 10 },
  { name: 'Dia Internacional da Sanidade Vegetal', group: 'Joaninhas', emoji: '🐞', taxonId: 48486, reason: 'Controlam pulgões sem veneno.', month: 5, day: 12 },
  { name: 'Dia do Zootecnista', group: 'Búfalo', emoji: '🐾', taxonId: 81925, reason: 'Um dos rebanhos estudados pela zootecnia; o Brasil tem o maior das Américas.', month: 5, day: 13 },
  { name: 'Dia das Mães', group: 'Orangotango', emoji: '🐾', taxonId: 43581, reason: 'A mãe cuida do filhote por cerca de oito anos.', month: 5, weekday: 0, nth: 2 },
  { name: 'Dia Internacional das Famílias', group: 'Sagui-de-tufos-pretos', emoji: '🐾', taxonId: 43374, reason: 'A família inteira ajuda a carregar e criar os filhotes.', month: 5, day: 15 },
  { name: 'Dia do Gari', group: 'Urubu-de-cabeça-preta', emoji: '🐦', taxonId: 4765, reason: 'O faxineiro da natureza.', month: 5, day: 16 },
  { name: 'Dia Internacional da Luz', group: 'Vaga-lumes', emoji: '🐞', taxonId: 47731, reason: 'Produzem a própria luz.', month: 5, day: 16 },
  { name: 'Dia dos Cientistas', group: 'Mosca-das-frutas', emoji: '🐞', taxonId: 1409656, reason: 'O organismo-modelo mais estudado da genética.', month: 5, day: 16 },
  { name: 'Dia Mundial da Reciclagem', group: 'Minhoca-californiana', emoji: '🌊', taxonId: 127409, reason: 'A minhoca da compostagem doméstica.', month: 5, day: 17 },
  { name: 'Dia Mundial das Telecomunicações', group: 'Golfinho-nariz-de-garrafa', emoji: '🐾', taxonId: 41482, reason: 'Cada um tem um assobio próprio, que funciona como nome.', month: 5, day: 17 },
  { name: 'Dia do Profissional de Física', group: 'Basilisco', emoji: '🦎', taxonId: 33117, reason: 'Corre sobre a água, um caso clássico de física animal.', month: 5, day: 19 },
  { name: 'Dia Internacional da Biodiversidade', group: 'Besouros', emoji: '🐞', taxonId: 47208, reason: 'A ordem de animais com mais espécies descritas.', month: 5, day: 22 },
  { name: 'Dia do Sol', group: 'Teiú', emoji: '🦎', taxonId: 318758, reason: 'Passa as manhãs tomando sol para se aquecer.', month: 5, day: 23 },
  { name: 'Dia da Lua', group: 'Urutau (mãe-da-lua)', emoji: '🐦', taxonId: 19667, reason: 'Canta em noites de lua; daí o nome popular.', month: 5, day: 24 },
  { name: 'Dia da Costureira', group: 'Bicho-da-seda', emoji: '🐞', taxonId: 143506, reason: 'Produz o fio da seda.', month: 5, day: 25 },
  { name: 'Dia Mundial do Futebol', group: 'Canário-da-terra', emoji: '🐦', taxonId: 9864, reason: 'A "seleção canarinho".', month: 5, day: 25 },
  { name: 'Dia Nacional da Mata Atlântica', group: 'Tiê-sangue', emoji: '🐦', taxonId: 10055, reason: 'Ave endêmica e símbolo da Mata Atlântica.', month: 5, day: 27 },
  { name: 'Dia do Ceramista', group: 'Vespa-oleira', emoji: '🐞', taxonId: 119344, reason: 'Molda ninhos de barro em forma de pote.', month: 5, day: 28 },
  { name: 'Dia Mundial do Meio Ambiente', group: 'Sapos, rãs e pererecas', emoji: '🐸', taxonId: 20979, reason: 'São os primeiros a sumir quando o ambiente adoece.', month: 6, day: 5 },
  { name: 'Dia da Língua Russa', group: 'Urso-pardo', emoji: '🐾', taxonId: 41641, reason: 'Símbolo tradicional da Rússia.', month: 6, day: 6 },
  { name: 'Dia Mundial dos Oceanos', group: 'Raia-manta', emoji: '🌊', taxonId: 623966, reason: 'Gigante dos oceanos, ameaçada pela pesca.', month: 6, day: 8 },
  { name: 'Dia Internacional do Brincar', group: 'Quati', emoji: '🐾', taxonId: 41670, reason: 'Os filhotes passam o dia em brincadeiras de luta.', month: 6, day: 11 },
  { name: 'Dia da Marinha Brasileira', group: 'Fragata', emoji: '🐦', taxonId: 4631, reason: 'Ave marinha que dá nome a um tipo de navio.', month: 6, day: 11 },
  { name: 'Dia dos Namorados', group: 'Cavalo-marinho', emoji: '🐟', taxonId: 102831, reason: 'Os casais "dançam" juntos todas as manhãs.', month: 6, day: 12 },
  { name: 'Dia de Santo Antônio', group: 'Sardinha', emoji: '🐟', taxonId: 118600, reason: 'O santo do "sermão aos peixes"; a sardinha é o prato das suas festas em Lisboa.', month: 6, day: 13 },
  { name: 'Dia Mundial do Doador de Sangue', group: 'Morcego-vampiro', emoji: '🐾', taxonId: 41168, reason: 'Divide o sangue que conseguiu com colegas que ficaram sem comer.', month: 6, day: 14 },
  { name: 'Dia Mundial de Combate à Desertificação e à Seca', group: 'Feneco', emoji: '🐾', taxonId: 42058, reason: 'A raposa do deserto, especialista em viver sem água.', month: 6, day: 17 },
  { name: 'Dia do Químico', group: 'Besouro-bombardeiro', emoji: '🐞', taxonId: 122211, reason: 'Mistura reagentes no abdome e dispara um jato fervente.', month: 6, day: 18 },
  { name: 'Dia da Imigração Japonesa no Brasil', group: 'Grou-da-manchúria (tsuru)', emoji: '🐦', taxonId: 39, reason: 'O tsuru dos origamis, símbolo de longevidade no Japão.', month: 6, day: 18 },
  { name: 'Dia do Vigilante', group: 'Ganso', emoji: '🐦', taxonId: 7018, reason: 'Usado como "cão de guarda" desde a Roma antiga.', month: 6, day: 20 },
  { name: 'Início do Inverno', group: 'Pinguim-de-magalhães', emoji: '🐦', taxonId: 3812, reason: 'Aparece no litoral do Sul e do Sudeste no inverno.', month: 6, day: 21 },
  { name: 'Dia Internacional do Yoga', group: 'Naja', emoji: '🦎', taxonId: 53492, reason: 'Inspira a "postura da cobra".', month: 6, day: 21 },
  { name: 'Dia do Orquidófilo', group: 'Abelhas-das-orquídeas', emoji: '🐞', taxonId: 416582, reason: 'Polinizam orquídeas em troca de perfume.', month: 6, day: 22 },
  { name: 'Dia do Lavrador', group: 'Garça-vaqueira', emoji: '🐦', taxonId: 411086, reason: 'Segue o arado e o gado para pegar insetos.', month: 6, day: 23 },
  { name: 'Dia Olímpico', group: 'Falcão-peregrino', emoji: '🐦', taxonId: 4647, reason: 'O animal mais rápido do mundo.', month: 6, day: 23 },
  { name: 'Dia de São João', group: 'Carneiro', emoji: '🐾', taxonId: 121578, reason: 'O carneirinho que acompanha o santo nas imagens.', month: 6, day: 24 },
  { name: 'Dia do Marítimo', group: 'Gaivotão', emoji: '🐦', taxonId: 4388, reason: 'Companhia certa de quem vive no mar.', month: 6, day: 25 },
  { name: 'Dia do Pescador / Dia de São Pedro', group: 'Tainha', emoji: '🐟', taxonId: 557622, reason: 'A pesca artesanal da tainha é tradição no litoral brasileiro.', month: 6, day: 29 },
  { name: 'Dia Internacional dos Trópicos', group: 'Tucano-toco', emoji: '🐦', taxonId: 18793, reason: 'Cartão-postal da fauna tropical.', month: 6, day: 29 },
  { name: 'Dia do Dublador', group: 'Sabiá-do-campo', emoji: '🐦', taxonId: 14878, reason: 'Imita o canto de outras aves.', month: 6, day: 29 },
  { name: 'Dia Internacional do Asteroide', group: 'Aves', emoji: '🐦', taxonId: 3, reason: 'São os dinossauros que sobreviveram ao asteroide.', month: 6, day: 30 },
  { name: 'Dia do Bombeiro Brasileiro', group: 'Cão (dálmata)', emoji: '🐾', taxonId: 47144, reason: 'Mascote tradicional dos bombeiros.', month: 7, day: 2 },
  { name: 'Dia Internacional das Cooperativas', group: 'Abelha-jataí', emoji: '🐞', taxonId: 1449239, reason: 'A colônia só funciona com todas cooperando.', month: 7, day: 5 },
  { name: 'Dia Mundial das Zoonoses', group: 'Carrapato-estrela', emoji: '🕷️', taxonId: 263533, reason: 'Transmite a febre maculosa.', month: 7, day: 6 },
  { name: 'Dia Mundial da Língua Kiswahili', group: 'Leão', emoji: '🐾', taxonId: 41964, reason: '"Simba" é leão em suaíli.', month: 7, day: 7 },
  { name: 'Dia Nacional da Ciência / do Pesquisador', group: 'Peixe-zebra', emoji: '🐟', taxonId: 49977, reason: 'Um dos animais mais usados em pesquisa.', month: 7, day: 8 },
  { name: 'Dia do Engenheiro de Minas', group: 'Rato-toupeira-pelado', emoji: '🐾', taxonId: 43746, reason: 'Cava quilômetros de túneis.', month: 7, day: 10 },
  { name: 'Dia do Engenheiro Florestal', group: 'Cutia', emoji: '🐾', taxonId: 43711, reason: 'Enterra sementes e "planta" castanheiras.', month: 7, day: 12 },
  { name: 'Dia Mundial do Rock', group: 'Besouros', emoji: '🐞', taxonId: 47208, reason: 'Beatles, os "besouros" do rock.', month: 7, day: 13 },
  { name: 'Dia do Cantor', group: 'Uirapuru', emoji: '🐦', taxonId: 72791, reason: 'Dono do canto mais lendário da Amazônia.', month: 7, day: 13 },
  { name: 'Dia do Engenheiro de Aquicultura', group: 'Tilápia', emoji: '🐟', taxonId: 121324, reason: 'O peixe mais criado no Brasil.', month: 7, day: 14 },
  { name: 'Dia de Proteção às Florestas', group: 'Bugio-ruivo', emoji: '🐾', taxonId: 74053, reason: 'Sentinela da floresta: adoece de febre amarela antes das pessoas.', month: 7, day: 17 },
  { name: 'Dia Internacional Nelson Mandela', group: 'Springbok', emoji: '🐾', taxonId: 42283, reason: 'Símbolo da seleção de rúgbi que Mandela usou para unir o país.', month: 7, day: 18 },
  { name: 'Dia do Amigo', group: 'Capivara', emoji: '🐾', taxonId: 74442, reason: 'Convive bem com praticamente qualquer bicho.', month: 7, day: 20 },
  { name: 'Dia Mundial do Xadrez', group: 'Cavalo', emoji: '🐾', taxonId: 209233, reason: 'A única peça do tabuleiro que é um animal.', month: 7, day: 20 },
  { name: 'Dia do Cantor Lírico', group: 'Curió', emoji: '🐦', taxonId: 367682, reason: 'Um dos cantos mais apreciados do Brasil.', month: 7, day: 22 },
  { name: 'Dia do Escritor', group: 'Lulas', emoji: '🐚', taxonId: 246133, reason: 'Carregam a própria tinta.', month: 7, day: 25 },
  { name: 'Dia dos Avós', group: 'Orca', emoji: '🐾', taxonId: 41521, reason: 'As avós lideram o grupo e aumentam a sobrevivência dos netos.', month: 7, day: 26 },
  { name: 'Dia Mundial dos Manguezais', group: 'Guará', emoji: '🐦', taxonId: 3750, reason: 'Ave vermelha dos manguezais brasileiros.', month: 7, day: 26 },
  { name: 'Dia do Agricultor', group: 'Anu-preto', emoji: '🐦', taxonId: 1971, reason: 'Come gafanhotos e outros insetos nas lavouras e pastos.', month: 7, day: 28 },
  { name: 'Dia Mundial da Conservação da Natureza', group: 'Arara-azul-de-lear', emoji: '🐦', taxonId: 18937, reason: 'Exemplo de recuperação: saiu de dezenas para mais de mil indivíduos.', month: 7, day: 28 },
  { name: 'Dia do Tintureiro', group: 'Cochonilha', emoji: '🐞', taxonId: 202089, reason: 'Inseto de onde se extrai o corante carmim.', month: 8, day: 3 },
  { name: 'Dia do Padre', group: 'Louva-a-deus', emoji: '🐞', taxonId: 48112, reason: 'Pela postura de quem reza.', month: 8, day: 4 },
  { name: 'Dia Interamericano da Qualidade do Ar', group: 'Canário', emoji: '🐦', taxonId: 9246, reason: 'Era levado às minas para avisar de gases tóxicos.', month: 8, day: 9 },
  { name: 'Dia Mundial do Canhoto', group: 'Canguru-vermelho', emoji: '🐾', taxonId: 1453439, reason: 'Estudos mostram que prefere usar a mão esquerda.', month: 8, day: 13 },
  { name: 'Dia dos Pais', group: 'Ema', emoji: '🐦', taxonId: 20512, reason: 'É o macho que choca os ovos e cria os filhotes.', month: 8, weekday: 0, nth: 2 },
  { name: 'Dia do Combate à Poluição', group: 'Mexilhão', emoji: '🐚', taxonId: 199357, reason: 'Filtra a água e acumula poluentes; é usado como bioindicador.', month: 8, day: 14 },
  { name: 'Dia do Analista de Sistemas', group: 'Píton', emoji: '🦎', taxonId: 32149, reason: 'A cobra que é símbolo da linguagem Python.', month: 8, day: 15 },
  { name: 'Dia do Filósofo', group: 'Mocho-galego', emoji: '🐦', taxonId: 19998, reason: 'A coruja de Atena, símbolo da filosofia.', month: 8, day: 16 },
  { name: 'Dia do Historiador', group: 'Elefante-africano', emoji: '🐾', taxonId: 43694, reason: 'A famosa "memória de elefante".', month: 8, day: 19 },
  { name: 'Dia do Folclore', group: 'Boto-cor-de-rosa', emoji: '🐾', taxonId: 41472, reason: 'Protagonista de uma das lendas mais conhecidas do país.', month: 8, day: 22 },
  { name: 'Dia do Susto', group: 'Gambá-de-orelha-preta', emoji: '🐾', taxonId: 42657, reason: 'Finge-se de morto quando leva um susto.', month: 8, day: 23 },
  { name: 'Dia do Soldado', group: 'Formiga-de-correição', emoji: '🐞', taxonId: 126834, reason: 'Marcha em colunas, com "soldados" de mandíbulas enormes.', month: 8, day: 25 },
  { name: 'Dia Mundial dos Lagos', group: 'Flamingos', emoji: '🐦', taxonId: 4256, reason: 'Vivem em lagos rasos e salinos.', month: 8, day: 27 },
  { name: 'Dia dos Bancários', group: 'Gralha-azul', emoji: '🐦', taxonId: 8481, reason: 'Enterra pinhões como poupança para o inverno.', month: 8, day: 28 },
  { name: 'Dia do Florista', group: 'Borboletas', emoji: '🐞', taxonId: 47224, reason: 'Visitantes mais assíduas das flores.', month: 9, day: 2 },
  { name: 'Dia Nacional do Biólogo', group: 'Tentilhões-de-darwin', emoji: '🐦', taxonId: 9476, reason: 'As aves que ajudaram Darwin a entender a evolução.', month: 9, day: 3 },
  { name: 'Dia da Amazônia', group: 'Pirarucu', emoji: '🐟', taxonId: 94494, reason: 'Um dos maiores peixes de água doce do mundo.', month: 9, day: 5 },
  { name: 'Dia do Alfaiate', group: 'Pássaro-alfaiate', emoji: '🐦', taxonId: 15347, reason: 'Costura folhas com fibras para fazer o ninho.', month: 9, day: 6 },
  { name: 'Dia do Médico Veterinário', group: 'Cão e gato', emoji: '🐾', taxonId: 47144, reason: 'Os pacientes mais frequentes.', month: 9, day: 9 },
  { name: 'Dia Nacional do Cerrado', group: 'Tatu-canastra', emoji: '🐾', taxonId: 47085, reason: 'O maior tatu do mundo, morador do Cerrado.', month: 9, day: 11 },
  { name: 'Dia do Árbitro Esportivo', group: 'Zebra', emoji: '🐾', taxonId: 43335, reason: 'Do uniforme listrado ao "deu zebra".', month: 9, day: 11 },
  { name: 'Dia do Programador', group: 'Mariposa', emoji: '🐞', taxonId: 47157, reason: 'O primeiro "bug" de computador foi uma mariposa presa num relé, em 1947.', month: 9, day: 13 },
  { name: 'Dia Internacional da Democracia', group: 'Abelha-europeia', emoji: '🐞', taxonId: 47219, reason: 'O enxame "vota" para escolher o novo ninho.', month: 9, day: 15 },
  { name: 'Dia Mundial pela Limpeza da Água', group: 'Libélulas', emoji: '🐞', taxonId: 47792, reason: 'Suas larvas são indicadoras de água limpa.', month: 9, day: 19 },
  { name: 'Dia Internacional da Limpeza das Praias', group: 'Maria-farinha', emoji: '🌊', taxonId: 53875, reason: 'O caranguejo das praias; some onde há lixo e pisoteio.', month: 9, day: 20 },
  { name: 'Dia da Árvore', group: 'Jacu', emoji: '🐦', taxonId: 2060, reason: 'Come frutos e espalha as sementes: "planta" árvores.', month: 9, day: 21 },
  { name: 'Dia Internacional da Paz', group: 'Pomba', emoji: '🐦', taxonId: 3017, reason: 'Símbolo da paz (mesma sugestão de 1º de janeiro).', month: 9, day: 21 },
  { name: 'Início da Primavera', group: 'Tesourinha', emoji: '🐦', taxonId: 16793, reason: 'Volta ao Sul e ao Sudeste na primavera para se reproduzir.', month: 9, day: 22 },
  { name: 'Dia Mundial dos Rios', group: 'Dourado', emoji: '🐟', taxonId: 195917, reason: 'O "rei do rio", que sobe a correnteza na piracema.', month: 9, day: 25 },
  { name: 'Dia do Hipnólogo', group: 'Choco', emoji: '🐚', taxonId: 119418, reason: 'Faz ondas de cor passarem pelo corpo para "hipnotizar" a presa.', month: 9, day: 25 },
  { name: 'Dia Mundial do Turismo', group: 'Golfinho-rotador', emoji: '🐾', taxonId: 41496, reason: 'Atração de Fernando de Noronha.', month: 9, day: 27 },
  { name: 'Dia Mundial contra a Raiva', group: 'Cães e morcegos', emoji: '🐾', taxonId: 47144, reason: 'Principais transmissores; vacinar os cães é a medida central.', month: 9, day: 28 },
  { name: 'Dia Mundial do Coração', group: 'Polvo-comum', emoji: '🐚', taxonId: 49315, reason: 'Tem três corações.', month: 9, day: 29 },
  { name: 'Dia Mundial do Tradutor', group: 'Papagaio-cinzento', emoji: '🐦', taxonId: 19269, reason: 'Alex, o papagaio que usava palavras com significado.', month: 9, day: 30 },
  { name: 'Dia Internacional do Idoso', group: 'Tartaruga-gigante-das-seychelles', emoji: '🦎', taxonId: 539233, reason: 'Jonathan, com mais de 190 anos, é o animal terrestre mais velho conhecido.', month: 10, day: 1 },
  { name: 'Dia Mundial do Vegetarianismo', group: 'Gorila', emoji: '🐾', taxonId: 43579, reason: 'Um gigante movido a folhas.', month: 10, day: 1 },
  { name: 'Dia Internacional da Não Violência', group: 'Bonobo', emoji: '🐾', taxonId: 43578, reason: 'Resolve conflitos com afeto em vez de briga.', month: 10, day: 2 },
  { name: 'Dia Mundial do Habitat', group: 'Caranguejo-ermitão', emoji: '🌊', taxonId: 47398, reason: 'Troca de casa conforme cresce.', month: 10, day: 5 },
  { name: 'Dia do Compositor Brasileiro', group: 'Baleia-jubarte', emoji: '🐾', taxonId: 41566, reason: 'Os machos compõem canções que mudam a cada temporada.', month: 10, day: 7 },
  { name: 'Dia Mundial do Algodão', group: 'Bicudo-do-algodoeiro', emoji: '🐞', taxonId: 199328, reason: 'A principal praga do algodão.', month: 10, day: 7 },
  { name: 'Dia do Nordestino', group: 'Asa-branca', emoji: '🐦', taxonId: 3102, reason: 'A ave da canção de Luiz Gonzaga.', month: 10, day: 8 },
  { name: 'Dia das Crianças', group: 'Lontras', emoji: '🐾', taxonId: 526556, reason: 'Os filhotes aprendem brincando.', month: 10, day: 12 },
  { name: 'Dia do Mar', group: 'Estrelas-do-mar', emoji: '🌊', taxonId: 47668, reason: 'Ícone da vida marinha.', month: 10, day: 12 },
  { name: 'Dia do Meteorologista', group: 'Andorinhas', emoji: '🐦', taxonId: 11853, reason: 'Diz o povo que voam baixo quando vem chuva.', month: 10, day: 14 },
  { name: 'Dia do Professor', group: 'Coruja-buraqueira', emoji: '🐦', taxonId: 19975, reason: 'A coruja é o símbolo do saber.', month: 10, day: 15 },
  { name: 'Dia Mundial da Alimentação', group: 'Mamangavas', emoji: '🐞', taxonId: 51111, reason: 'Sem elas não há maracujá: são as polinizadoras da planta.', month: 10, day: 16 },
  { name: 'Dia da Ciência e Tecnologia', group: 'Lagartixa', emoji: '🦎', taxonId: 68492, reason: 'As patas que grudam em tudo inspiraram novos adesivos.', month: 10, day: 16 },
  { name: 'Dia do Eletricista', group: 'Poraquê', emoji: '🐟', taxonId: 99786, reason: 'O peixe-elétrico da Amazônia.', month: 10, day: 17 },
  { name: 'Dia Nacional da Vacinação', group: 'Vaca', emoji: '🐾', taxonId: 74113, reason: '"Vacina" vem de "vacca": a primeira veio da varíola bovina.', month: 10, day: 17 },
  { name: 'Dia do Profissional da Propaganda', group: 'Pavão', emoji: '🐦', taxonId: 1204, reason: 'Mestre em chamar atenção.', month: 10, day: 17 },
  { name: 'Dia do Médico', group: 'Cobra-de-esculápio', emoji: '🦎', taxonId: 74009, reason: 'A serpente do bastão que simboliza a medicina.', month: 10, day: 18 },
  { name: 'Dia do Pintor', group: 'Saíra-sete-cores', emoji: '🐦', taxonId: 9557, reason: 'Parece pintada à mão.', month: 10, day: 18 },
  { name: 'Dia do Guarda Noturno', group: 'Corujinha-do-mato', emoji: '🐦', taxonId: 19788, reason: 'Vigia a noite das cidades brasileiras.', month: 10, day: 19 },
  { name: 'Dia do Profissional de Informática', group: 'Pinguim', emoji: '🐦', taxonId: 3806, reason: 'Tux, o mascote do Linux.', month: 10, day: 19 },
  { name: 'Dia do Poeta', group: 'Sabiá-laranjeira', emoji: '🐦', taxonId: 12738, reason: 'O pássaro dos poetas brasileiros (mesma sugestão de 21 de março).', month: 10, day: 20 },
  { name: 'Dia Mundial do Controlador de Tráfego Aéreo', group: 'Estorninho', emoji: '🐦', taxonId: 14850, reason: 'Milhares voam juntos sem colidir.', month: 10, day: 20 },
  { name: 'Dia do Paraquedista', group: 'Esquilos-voadores', emoji: '🐾', taxonId: 339576, reason: 'Planam de árvore em árvore.', month: 10, day: 22 },
  { name: 'Dia do Aviador', group: 'Andorinhão-preto', emoji: '🐦', taxonId: 6638, reason: 'Passa até dez meses no ar sem pousar.', month: 10, day: 23 },
  { name: 'Dia do Dentista', group: 'Peixe-papagaio', emoji: '🐟', taxonId: 516508, reason: 'Tem os dentes fundidos num "bico" capaz de roer coral.', month: 10, day: 25 },
  { name: 'Dia do Sapateiro', group: 'Piolho-de-cobra', emoji: '🌊', taxonId: 47735, reason: 'Centenas de pés para calçar.', month: 10, day: 25 },
  { name: 'Dia do Engenheiro Civil', group: 'Aranhas-de-teia-orbicular', emoji: '🕷️', taxonId: 47535, reason: 'A teia é uma obra de engenharia estrutural.', month: 10, day: 25 },
  { name: 'Dia do Trabalhador da Construção Civil', group: 'João-de-barro', emoji: '🐦', taxonId: 11275, reason: 'Constrói a própria casa de barro.', month: 10, day: 26 },
  { name: 'Dia do Designer de Interiores', group: 'Pássaros-caramancheiros', emoji: '🐦', taxonId: 14495, reason: 'O macho decora seu caramanchão com objetos coloridos para atrair a fêmea.', month: 10, day: 30 },
  { name: 'Dia das Bruxas (Halloween)', group: 'Caranguejeiras', emoji: '🕷️', taxonId: 47424, reason: 'Presença certa na decoração da data.', month: 10, day: 31 },
  { name: 'Dia do Saci', group: 'Saci (a ave)', emoji: '🐦', taxonId: 1989, reason: 'O canto dela, que parece dizer "sa-ci", está ligado à lenda.', month: 10, day: 31 },
  { name: 'Dia Mundial das Cidades', group: 'Bem-te-vi', emoji: '🐦', taxonId: 16956, reason: 'Uma das aves mais bem adaptadas às cidades brasileiras.', month: 10, day: 31 },
  { name: 'Dia do Inventor', group: 'Macaco-prego', emoji: '🐾', taxonId: 516974, reason: 'Usa pedras como martelo e bigorna para quebrar cocos.', month: 11, day: 4 },
  { name: 'Dia do Designer Gráfico', group: 'Camaleões', emoji: '🦎', taxonId: 32805, reason: 'Especialistas em cor.', month: 11, day: 5 },
  { name: 'Dia da Floresta e do Clima', group: 'Queixada', emoji: '🐾', taxonId: 42115, reason: 'Engenheiro da floresta: revolve o solo e espalha sementes.', month: 11, day: 7 },
  { name: 'Dia Mundial do Urbanismo', group: 'Cão-da-pradaria', emoji: '🐾', taxonId: 46175, reason: 'Constrói "cidades" subterrâneas com bairros e túneis.', month: 11, day: 8 },
  { name: 'Dia do Radiologista', group: 'Pererecas-de-vidro', emoji: '🐸', taxonId: 21218, reason: 'A barriga transparente deixa ver os órgãos, como um raio-X.', month: 11, day: 8 },
  { name: 'Dia Mundial do Diabetes', group: 'Monstro-de-gila', emoji: '🦎', taxonId: 35003, reason: 'Um remédio para diabetes foi criado a partir da sua saliva.', month: 11, day: 14 },
  { name: 'Dia do Joalheiro', group: 'Ostras-perlíferas', emoji: '🐚', taxonId: 204980, reason: 'Fabricam pérolas.', month: 11, day: 15 },
  { name: 'Dia da Bandeira Nacional', group: 'Arara-canindé', emoji: '🐦', taxonId: 19018, reason: 'Veste o azul e o amarelo da bandeira.', month: 11, day: 19 },
  { name: 'Dia Mundial do Banheiro', group: 'Vombate', emoji: '🐾', taxonId: 43009, reason: 'O único animal que faz cocô em cubos.', month: 11, day: 19 },
  { name: 'Dia do Músico', group: 'Araponga', emoji: '🐦', taxonId: 8854, reason: 'O canto soa como um martelo na bigorna.', month: 11, day: 22 },
  { name: 'Dia do Rio', group: 'Ariranha', emoji: '🐾', taxonId: 41845, reason: 'A "onça-d\'água" dos rios brasileiros.', month: 11, day: 24 },
  { name: 'Dia Nacional de Combate à Dengue', group: 'Mosquito-da-dengue', emoji: '🐞', taxonId: 155453, reason: 'É o transmissor da dengue.', month: 11, day: 25 },
  { name: 'Dia do Perito Criminal', group: 'Moscas-varejeiras', emoji: '🐞', taxonId: 61860, reason: 'A entomologia forense usa suas larvas para estimar a hora da morte.', month: 12, day: 4 },
  { name: 'Dia Mundial do Solo', group: 'Colêmbolos', emoji: '🌊', taxonId: 49470, reason: 'Minúsculos recicladores que mantêm o solo vivo.', month: 12, day: 5 },
  { name: 'Dia Internacional do Voluntariado', group: 'Suricato', emoji: '🐾', taxonId: 41943, reason: 'Revezam-se como sentinelas e babás do grupo.', month: 12, day: 5 },
  { name: 'Dia Internacional da Aviação Civil', group: 'Condor-dos-andes', emoji: '🐦', taxonId: 4747, reason: 'Uma das maiores aves voadoras do mundo.', month: 12, day: 7 },
  { name: 'Dia Universal do Palhaço', group: 'Peixe-palhaço', emoji: '🐟', taxonId: 132688, reason: 'Pelo nome e pelas cores.', month: 12, day: 10 },
  { name: 'Dia Internacional das Montanhas', group: 'Vicunha', emoji: '🐾', taxonId: 1624576, reason: 'Vive acima dos 3.200 metros nos Andes.', month: 12, day: 11 },
  { name: 'Dia do Marinheiro', group: 'Atobá-pardo', emoji: '🐦', taxonId: 3797, reason: 'Ave marinha comum em toda a costa brasileira.', month: 12, day: 13 },
  { name: 'Dia do Jardineiro', group: 'Sapo-cururu', emoji: '🐸', taxonId: 67107, reason: 'Come as pragas do jardim.', month: 12, day: 13 },
  { name: 'Dia do Arquiteto', group: 'Cupins', emoji: '🐞', taxonId: 118903, reason: 'Os cupinzeiros têm ventilação natural que inspira prédios.', month: 12, day: 13 },
  { name: 'Dia do Ótico', group: 'Gavião-carijó', emoji: '🐦', taxonId: 201041, reason: 'As aves de rapina têm a visão mais aguçada entre os animais.', month: 12, day: 13 },
  { name: 'Dia do Museólogo', group: 'Celacanto', emoji: '🌊', taxonId: 89359, reason: 'O "fóssil vivo": era dado como extinto havia 66 milhões de anos.', month: 12, day: 18 },
  { name: 'Dia da Língua Árabe', group: 'Órix-da-arábia', emoji: '🐾', taxonId: 42309, reason: 'Animal nacional de vários países árabes.', month: 12, day: 18 },
  { name: 'Início do Verão', group: 'Tartaruga-cabeçuda', emoji: '🦎', taxonId: 39665, reason: 'É a época da desova nas praias brasileiras.', month: 12, day: 21 },
  { name: 'Natal', group: 'Rena', emoji: '🐾', taxonId: 42199, reason: 'Puxa o trenó do Papai Noel.', month: 12, day: 25 },
  { name: 'Dia da Esperança', group: 'Esperança (o inseto)', emoji: '🐞', taxonId: 48124, reason: 'O grilo verde que, diz a crença, traz boa sorte.', month: 12, day: 31 },
]
