// Demais datas do calendário "Datas Comemorativas" (edição de 2025), mostradas só como lembrete do dia.
// Chave: mês-dia. As datas são tratadas como fixas em qualquer ano.

export const REMINDERS: Record<string, string[]> = {
  '01-01': ['Ano Novo'],
  '01-02': ['Dia do Sanitarista'],
  '01-03': ['Dia do Hemofílico', 'Dia da Abreugrafia'],
  '01-04': ['Dia do Hemofílico'],
  '01-05': ['Dia Nacional da Tipografia'],
  '01-06': ['Dia da Gratidão'],
  '01-07': ['Dia do Mensageiro', 'Dia da Liberdade de Culto'],
  '01-09': ['Dia do Fico (em 1822)'],
  '01-10': ['Dia de São Gonçalo', 'Dia de Peculiar People Play'],
  '01-11': ['Dia de São Teodósio', 'Dia do Controle da Poluição por Agrotóxicos', 'Dia do Combate da Poluição por Agrotóxicos'],
  '01-12': ['Dia do Empresário Contábil'],
  '01-14': ['Dia do Sargento', 'Dia do Treinador de Futebol'],
  '01-15': ['Dia do Compositor'],
  '01-16': ['Dia do Fisiatra Veterinário', 'Dia do Cortador de Cana-de-Açúcar'],
  '01-17': ['Dia do Protetor dos Animais'],
  '01-18': ['Dia da Manicure'],
  '01-19': ['Dia Mundial do Terapeuta Ocupacional', 'Dia Oficial do Cabeleireiro'],
  '01-20': ['Dia da Parteira Tradicional'],
  '01-24': ['Dia Mundial da Educação'],
  '01-26': ['Dia Internacional da Energia Limpa'],
  '01-27': ['Dia do Orador', 'Dia Internacional em Memória das Vítimas do Holocausto', 'Dia da Proclamação da Declaração dos Direitos dos Animais'],
  '01-28': ['Dia do Auditor Fiscal do Trabalho', 'Dia do Portuário'],
  '01-29': ['Dia Nacional da Visibilidade Trans', 'Dia Nacional de Combate e Prevenção da Hanseníase', 'Dia Mundial Contra a Hanseníase'],
  '01-30': ['Dia do Quadrinho Nacional'],
  '01-31': ['Dia do Engenheiro Ambiental'],
  '02-01': ['Semana Nacional de Prevenção da Gravidez na Adolescência', 'Dia do Publicitário', 'Semana Mundial da Harmonia Inter-religiosa'],
  '02-02': ['Dia da Apresentação de Jesus no Templo', 'Dia de Nossa Senhora dos Navegantes', 'Dia do Agente Fiscal'],
  '02-04': ['Dia Internacional da Fraternidade Humana', 'Dia Mundial do Câncer'],
  '02-05': ['Dia Nacional da Mamografia', 'Dia do Dermatologista'],
  '02-06': ['Dia do Agente de Defesa Ambiental', 'Dia Internacional de Tolerância Zero à Mutilação Genital Feminina'],
  '02-07': ['Dia do Gráfico'],
  '02-09': ['Dia Mundial da Pizza'],
  '02-10': ['Dia Mundial das Leguminosas', 'Dia do Atleta Profissional'],
  '02-11': ['Dia do Zelador', 'Dia Internacional das Mulheres e Meninas na Ciência'],
  '02-12': ['Dia Internacional de Prevenção do Extremismo Violento'],
  '02-13': ['Dia Mundial do Rádio'],
  '02-15': ['Dia Internacional do Câncer na Infância'],
  '02-16': ['Dia do Repórter'],
  '02-17': ['Dia Mundial da Resiliência do Turismo'],
  '02-18': ['Dia da Baleia'],
  '02-19': ['Dia Mundial das Baleias'],
  '02-20': ['Dia Nacional de Combate às Drogas e Alcoolismo', 'Dia Mundial da Justiça Social'],
  '02-22': ['Dia Nacional da Criação do Ibama', 'Dia do Auxiliar de Serviços Gerais', 'Aniversário do IBAMA'],
  '02-24': ['Promulgação da primeira Constituição da República do Brasil (1891)'],
  '02-27': ['Dia Internacional de Ação pelos Golfinhos', 'Dia do Agente Fiscal da Receita Federal'],
  '02-28': ['Dia Nacional de Doenças Raras'],
  '03-01': ['Dia da Discriminação Zero'],
  '03-02': ['Aniversário do serviço Florestal Brasileiro – SFB'],
  '03-04': ['Dia Mundial da Obesidade'],
  '03-05': ['Dia Internacional de Conscientização sobre Desarmamento e Não Proliferação'],
  '03-07': ['Dia do Fuzileiro Naval'],
  '03-08': ['Dia Internacional da Mulher'],
  '03-09': ['Dia do DJ'],
  '03-10': ['Dia Internacional das Mulheres Juízas'],
  '03-12': ['Dia do Bibliotecário'],
  '03-14': ['Dia Mundial de Luta dos Atingidos por Barragens', 'Dia Nacional dos Animais'],
  '03-15': ['Dia Internacional da Luta contra a Caça de Focas', 'Dia Internacional de Combate à Islamofobia', 'Dia do Consumidor'],
  '03-16': ['Dia Mundial do Urso Panda', 'Dia Nacional do Ouvidor', 'Dia do Agente Penitenciário Federal', 'Dia Internacional do Cavalo'],
  '03-19': ['Dia do Caráter', 'Dia da Escola', 'Dia do Consertador'],
  '03-20': ['Dia Mundial da Saúde Bucal'],
  '03-21': ['Dia Florestal Mundial', 'Dia Internacional do Nowruz', 'Semana de Solidariedade com os Povos em Luta contra o Racismo', 'Dia Internacional da Síndrome de Down', 'Dia Internacional pela Eliminação da Discriminação Racial'],
  '03-24': ['Dia Mundial de Combate à Tuberculose', 'Dia Internacional pelo Direito à Verdade e pela Dignidade das Vítimas', 'Aniversário da Secretaria do Meio Ambiente'],
  '03-25': ['Dia Internacional de Solidariedade com os Funcionários Detidos e Desaparecidos', 'Dia Internacional em Memória das Vítimas da Escravidão e do Tráfico Transatlântico de Escravizados'],
  '03-27': ['Dia do Graffiti'],
  '03-28': ['Dia do Revisor', 'Dia do Diagramador', 'Dia Estadual da Consciência Ecológica – ES Lei 9267/09'],
  '03-31': ['Dia da Saúde e da Nutrição'],
  '04-01': ['Dia da Abolição da Escravidão dos Índios - 1680'],
  '04-02': ['Semana da Saúde no Brasil', 'Dia Mundial de Conscientização Sobre o Autismo', 'Dia do Propagandista'],
  '04-04': ['Dia Nacional do Parkinsoniano', 'Dia Mundial dos Animais', 'Dia Internacional de Conscientização sobre Minas Terrestres'],
  '04-05': ['Dia do Propagandista Farmacêutico', 'Dia Internacional da Consciência'],
  '04-06': ['Dia Mundial da Atividade Física', 'Dia Nacional de Mobilização pela Promoção da Saúde e Qualidade de Vida', 'Dia Internacional do Esporte para o Desenvolvimento e a Paz'],
  '04-07': ['Dia da Mundial da Saúde', 'Dia do Corretor', 'Dia do Médico Legista', 'Dia do Jornalista', 'Dia Internacional de Reflexão sobre o Genocídio de 1994 em Ruanda'],
  '04-08': ['Dia Mundial de Combate ao Câncer', 'Dia Nacional do Sistema Braile'],
  '04-10': ['Dia do Engenheiro Metalurgista'],
  '04-11': ['Dia do Infectologista'],
  '04-12': ['Dia do Obstetra'],
  '04-13': ['Dia do Office Boy'],
  '04-14': ['Dia do Neurocirurgião', 'Dia Mundial da Doença de Chagas', 'Dia do Técnico em Serviço de Saúde'],
  '04-15': ['Dia Internacional do Ciclista', 'Dia do Desarmamento Infantil'],
  '04-17': ['Dia Internacional da Hemofilia'],
  '04-18': ['Dia Mundial do Radiamador'],
  '04-19': ['Dia do Índio'],
  '04-20': ['Dia do Diplomata'],
  '04-21': ['Dia de Tiradentes (Inconfidência Mineira)', 'Dia do Funcionário Policial Civil', 'Dia do Metalúrgico', 'Inauguração de Brasília (1960)'],
  '04-22': ['Dia do Agente de Viagem'],
  '04-23': ['Dia do Serralheiro', 'Dia Mundial do Livro e do Direito de Autor'],
  '04-24': ['Dia Mundial do Livro', 'Dia Mundial de Enfrentamento à Meningite', 'Semana Mundial da Imunização', 'Semana de Vacinação nas Américas', 'Dia Internacional do Multilateralismo e da Diplomacia pela Paz', 'Dia Internacional das Meninas nas Tecnologias da Informação', 'Dia de Libras (Língua Brasileira de Sinais)'],
  '04-25': ['Dia do Despachante Aduaneiro', 'Dia Internacional do Delegado', 'Dia do Profissional da Contabilidade'],
  '04-26': ['Dia Nacional de Prevenção e Enfrentamento à Hipertensão Arterial', 'Dia do Engraxate', 'Dia Mundial da Propriedade Intelectual', 'Dia do Juiz Trabalhista'],
  '04-27': ['Dia da Empregada Doméstica'],
  '04-28': ['Dia Mundial da Segurança e Saúde no Trabalho', 'Dia Nacional em Memória das Vítimas de Acidentes e Doenças do Trabalho', 'Dia da Educação', 'Dia da Sogra'],
  '04-30': ['Dia do Ferroviário', 'Dia Internacional do Jazz', 'Dia Nacional da Mulher'],
  '05-01': ['Maio Amarelo (Prevenção de Acidentes no Trânsito)'],
  '05-03': ['Dia do Pau-Brasil', 'Dia Mundial da Liberdade de Imprensa', 'Dia do Taquígrafo', 'Dia do Solo e do Pau-Brasil'],
  '05-05': ['Dia Nacional do Uso Racional de Medicamento', 'Dia Internacional da Parteira'],
  '05-06': ['Dia do Psicanalista'],
  '05-07': ['Dia do Oftalmologista', 'Dia Mundial da Saúde'],
  '05-08': ['Dia Mundial das Aves Migratórias', 'Dia do Artista Plástico Brasileiro', 'Dias de Memória e Reconciliação pelas Vítimas da Segunda Guerra Mundial', 'Dia do Profissional de Marketing'],
  '05-10': ['Dia Mundial das Aves Migratórias', 'Dia do Campo', 'Dia Mundial do Frango', 'Dia da Cozinheira'],
  '05-12': ['Dia Internacional da Enfermagem e do Enfermeiro', 'Dia do Engenheiro Militar'],
  '05-13': ['Dia da Abolição da Escravatura', 'Dia do Chefe de Cozinha', 'Dia de Nossa Senhora de Fátima'],
  '05-15': ['Dia do Gerente Bancário', 'Semana de Conscientização sobre as Doenças Inflamatórias Intestinais', 'Dia Nacional do Controle das Infecções Hospitalares', 'Semana Mundial da Segurança no Trânsito', 'Dia do Assistente Social', 'Dia do Cortejo'],
  '05-16': ['Dia Internacional da Convivência em Paz'],
  '05-17': ['Dia das Espécies Ameaçadas', 'Dia Internacional da Luta Contra à Homofobia', 'Dia Internacional da Comunicação', 'Dia Mundial da Hipertensão Arterial'],
  '05-18': ['Dia das Raças Indígenas da América', 'Dia dos Vidraceiros', 'Dia Nacional da Luta Antimanicomial', 'Dia Nacional de Combate ao Abuso e à Exploração Sexual de Crianças e Adolescentes'],
  '05-19': ['Dia Mundial do Fair Play', 'Dia e Semana Nacional de Doação do Leite Humano', 'Dia Mundial da Doença Inflamatória Intestinal', 'Dia Mundial de Doação do Leite Humano', 'Dia do Defensor Público'],
  '05-20': ['Dia Nacional do Técnico e Auxiliar de Enfermagem', 'Dia do Pedagogo', 'Dia do Comissário de Menores'],
  '05-21': ['Dia Mundial da Diversidade Cultural', 'Dia Internacional do Chá'],
  '05-22': ['Dia Nacional das Diversidades Biológicas', 'Dia do Apicultor'],
  '05-23': ['Dia da Colonização do Solo', 'Dia Internacional pelo Fim da Fístula Obstétrica'],
  '05-24': ['Dia do Telegrafista', 'Dia da Indústria Gráfica', 'Dia do Datilógrafo'],
  '05-25': ['Dia do Orgulho Nerd', 'Semana de Solidariedade com os Povos dos Territórios Não Autônomos', 'Dia do Massagista', 'Dia do Trabalhador Rural', 'Dia da Indústria e do Industrial'],
  '05-26': ['Dia do Revendedor Lotérico', 'Dia Nacional de Enfrentamento ao Glaucoma'],
  '05-27': ['Dia Nacional da Floresta Atlântica', 'Dia do Profissional Liberal'],
  '05-28': ['Dia Mundial Contra a Mortalidade Materna', 'Dia Nacional de Redução da Mortalidade Materna', 'Dia Internacional de Luta Pela Saúde da Mulher', 'Dia de Ação pela Saúde da Mulher'],
  '05-29': ['Dia Mundial da Saúde Digestiva', 'Dia Mundial da Lontra', 'Dia do Geógrafo e do Estatístico — Instituto Brasileiro de Geografia e Estatística (IBGE)', 'Dia Internacional dos Soldados da Paz da ONU'],
  '05-30': ['Dia Internacional da Lontra', 'Dia do Geólogo', 'Dia do Decorador', 'Dia Internacional da Batata', 'Dia Mundial da Esclerose Múltipla'],
  '05-31': ['Dia Mundial sem Tabaco', 'Semana Nacional do Meio Ambiente', 'Dia da Aeromoça e do Comissário de Voo'],
  '06-01': ['Dia Mundial dos Pais e Mães'],
  '06-03': ['Dia do Profissional de Recursos Humanos', 'Dia Mundial da Bicicleta', 'Dia Nacional da Educação Ambiental', 'Dia Internacional do Administrador de Pessoal e da Comunidade Social'],
  '06-04': ['Dia do Engenheiro Agrimensor', 'Dia de Abraçar seu Gato', 'Dia Internacional das Crianças Vítimas de Agressão'],
  '06-05': ['Dia Mundial do Meio Ambiente e da Ecologia', 'Dia da Ecologia', 'Dia Nacional da Reciclagem'],
  '06-06': ['Dia Nacional de Luta contra Queimaduras', 'Dia Nacional do Teste do Pezinho'],
  '06-07': ['Dia Mundial da Segurança dos Alimentos'],
  '06-08': ['Dia do Cunhado', 'Dia do Citricultor', 'Dia do Oceanógrafo'],
  '06-09': ['Dia da Imunização', 'Dia do Porteiro', 'Dia do Tenista'],
  '06-10': ['Dia Internacional do Diálogo entre Civilizações'],
  '06-11': ['Dia do Educador Sanitário'],
  '06-12': ['Dia Mundial contra o Trabalho Infantil'],
  '06-13': ['Dia Internacional de Conscientização sobre o Albinismo'],
  '06-14': ['Dia do Solista'],
  '06-15': ['Dia Mundial de Conscientização da Violência contra a Pessoa Idosa', 'Dia do Patologista Veterinário'],
  '06-16': ['Dia Internacional das Remessas Familiares'],
  '06-17': ['Dia Mundial dos Crocodilianos', 'Dia do Gestor Comercial'],
  '06-18': ['Dia Internacional de Combate ao Discurso de Ódio', 'Dia da Gastronomia Sustentável'],
  '06-19': ['Dia Internacional pela Eliminação da Violência Sexual em Conflitos', 'Dia Nacional do Luto', 'Dia Mundial de Conscientização sobre a Doença Falciforme', 'Dia do Cinema Brasileiro'],
  '06-20': ['Dia do Advogado Trabalhista', 'Dia Mundial do Refugiado', 'Dia do Revendedor'],
  '06-21': ['Dia do Profissional de Mídia', 'Dia Internacional da Celebração do Solstício'],
  '06-22': ['Dia do Economiário', 'Dia do Aeroviário'],
  '06-23': ['Dia Nacional do Agente Marítimo', 'Dia do Serviço Público das Nações Unidas', 'Dia Internacional das Viúvas', 'Dia Internacional das Mulheres na Engenharia', 'Dia Olímpico e do Atleta Olímpico'],
  '06-24': ['Dia do Observador Aéreo', 'Dia Nacional do Policial e do Bombeiro Militares', 'Dia Internacional das Mulheres na Diplomacia'],
  '06-26': ['Dia do Metrologista', 'Dia Nacional do Diabetes', 'Dia Internacional contra o Abuso e o Tráfico Ilícito de Drogas', 'Dia Internacional de Apoio às Vítimas de Tortura'],
  '06-27': ['Dia Nacional do Quadrilheiro Junino'],
  '06-28': ['Dia Internacional do Orgulho LGBTQIA+'],
  '06-29': ['Dia do Telefonista', 'Dia do Pescador Amador', 'Dia do Papa', 'Dia do Engenheiro de Petróleo', 'Dia de São Paulo (Santo)'],
  '06-30': ['Dia Nacional do Fiscal Federal Agropecuário', 'Dia Internacional do Parlamentarismo'],
  '07-01': ['Julho Amarelo - Mês de luta contra as hepatites virais', 'Dia da Vacina BCG'],
  '07-02': ['Dia do Hospital', 'Independência da Bahia'],
  '07-04': ['Dia Mundial do Golfinho', 'Dia do Operador de Telemarketing'],
  '07-06': ['Dia Mundial de Combate às Zoonoses'],
  '07-08': ['Dia do Panificador'],
  '07-10': ['Dia da Saúde Ocular', 'Aniversário de criação do Fundo Nacional do Meio Ambiente'],
  '07-11': ['Dia Internacional de Reflexão e Memória do Genocídio de 1995 em Srebrenica', 'Dia Mundial da População'],
  '07-12': ['Dia Internacional de Combate às Tempestades de Areia e Poeira', 'Dia Internacional da Esperança'],
  '07-13': ['Dia dos Compositores e Cantores Sertanejos', 'Dia do Estatuto da Criança e do Adolescente', 'Dia do Engenheiro de Saneamento'],
  '07-14': ['Dia do Administrador Hospitalar', 'Dia do Propagandista de Laboratório'],
  '07-15': ['Dia Nacional do Pecuarista', 'Dia Mundial das Habilidades dos Jovens', 'Dia dos Homens'],
  '07-16': ['Dia do Comerciante'],
  '07-19': ['Dia do Vaqueiro Nordestino'],
  '07-20': ['Dia Pan-americano do Engenheiro', 'Dia Internacional da Lua'],
  '07-21': ['Dia Nacional do Garimpeiro'],
  '07-23': ['Dia do Guarda Rodoviário'],
  '07-24': ['Dia Nacional do Suinocultor'],
  '07-25': ['Dia do Motorista', 'Dia do Colono', 'Dia Internacional das Mulheres e Meninas Afrodescendentes', 'Dia Mundial de Prevenção do Afogamento', 'Aniversário de Criação do Ministério da Saúde'],
  '07-26': ['Dia Nacional do Arqueólogo'],
  '07-27': ['Dia Mundial de Conscientização e Enfrentamento ao Câncer de Cabeça e Pescoço', 'Dia do Motociclista', 'Dia do Pediatra', 'Dia Nacional da Prevenção de Acidentes do Trabalho'],
  '07-28': ['Dia Mundial de Luta Contra as Hepatites Virais'],
  '07-30': ['Dia Internacional da Amizade', 'Dia Mundial contra o Tráfico de Pessoas'],
  '07-31': ['Dia Mundial do Guarda-Florestal', 'Dia do Vira-lata'],
  '08-01': ['Semana Mundial da Amamentação', 'Mês do Aleitamento Materno no Brasil', 'Dia do Cerealista'],
  '08-04': ['Dia do Sacerdote'],
  '08-05': ['Dia do Nascimento de Oswaldo Cruz', 'Dia da Farmácia', 'Dia Nacional da Saúde', 'Dia Nacional da Vigilância Sanitária'],
  '08-06': ['Dia Nacional dos Profissionais da Educação'],
  '08-08': ['Dia Nacional de Prevenção e Controle do Colesterol'],
  '08-09': ['Dia Internacional dos Povos Indígenas'],
  '08-10': ['Semana Nacional de Controle e Combate à Leishmaniose'],
  '08-11': ['Dia do Estudante', 'Dia do Garçom', 'Dia do Advogado', 'Dia Mundial do Steelpan', 'Dia do Magistrado'],
  '08-12': ['Dia Internacional da Juventude'],
  '08-13': ['Dia do Economista'],
  '08-14': ['Dia do Cardiologista', 'Dia do Controle da Poluição Industrial'],
  '08-15': ['Assunção de Nossa Senhora'],
  '08-16': ['Dia do Auxiliar de Almoxarifado'],
  '08-17': ['Dia do Gato Preto'],
  '08-19': ['Dia Mundial Humanitário', 'Dia do Artista de Teatro'],
  '08-21': ['Semana Nacional da Pessoa com Deficiência Intelectual e Múltipla', 'Dia Internacional em Memória das Vítimas do Terrorismo'],
  '08-22': ['Dia do Supervisor e Coordenador', 'Dia Internacional em Memória das Vítimas de Violência por Religião ou Crença'],
  '08-23': ['Dia Internacional em Memória do Tráfico de Escravizados e de sua Abolição', 'Dia do Aviador Naval'],
  '08-25': ['Dia do Miojo', 'Dia do Feirante'],
  '08-26': ['Dia Internacional do Animal Abandonado', 'Dia Mundial do Cachorro', 'Dia do Catequista', 'Dia do Nascimento de Albert Sabin'],
  '08-27': ['Dia do Corretor de Imóveis', 'Dia do Avicultor', 'Dia da Limpeza Urbana', 'Dia do Psicólogo'],
  '08-28': ['Aniversário do Instituto Chico Mendes de Conservação da Biodiversidade – ICMBio'],
  '08-29': ['Dia Internacional contra os Testes Nucleares', 'Dia Nacional de Enfrentamento ao Fumo'],
  '08-30': ['Dia Internacional das Vítimas de Desaparecimentos Forçados', 'Dia Nacional de Conscientização sobre a Esclerose Múltipla'],
  '08-31': ['Dia do Nutricionista', 'Dia Internacional dos Afrodescendentes'],
  '09-01': ['Dia do Profissional de Educação Física'],
  '09-02': ['Dia do Repórter Fotográfico'],
  '09-05': ['Dia Internacional da Caridade', 'Dia dos Irmãos', 'Dia do Oficial de Farmácia do Brasil'],
  '09-07': ['Dia Internacional da Cooperação Policial', 'Dia da Proclamação da Independência do Brasil', 'Dia Internacional de Conscientização sobre Distrofia Muscular de Duchenne', 'Dia Internacional do Ar Limpo para um Céu Azul'],
  '09-08': ['Dia Internacional da Alfabetização'],
  '09-09': ['Dia Internacional para Proteger a Educação de Ataques', 'Dia do Administrador'],
  '09-10': ['Dia Nacional do Assessor de Imprensa', 'Dia Mundial de Prevenção ao Suicídio'],
  '09-12': ['Dia das Nações Unidas para a Cooperação Sul-Sul', 'Dia do Operador de Rastreamento'],
  '09-13': ['Dia do Agrônomo'],
  '09-14': ['Dia Internacional da Capivara'],
  '09-15': ['Dia do Cliente'],
  '09-16': ['Dia Internacional para a Prevenção de Desastres Naturais', 'Dia Internacional de Preservação da Camada de Ozônio', 'Dia do Caminhoneiro', 'Dia Internacional da Cardiologia Intervencionista', 'Dia Internacional de Proteção da Camada de Ozônio'],
  '09-17': ['Dia Mundial da Segurança do Paciente', 'Dia da Compreensão entre os Homens'],
  '09-18': ['Dia Mundial de Limpeza do Litoral', 'Dia Internacional da Igualdade Salarial'],
  '09-19': ['Dia do Ortopedista', 'Aniversário do SUS', 'Dia Nacional do Educador Social', 'Dia Internacional de Atenção aos Acidentes Ofídicos'],
  '09-20': ['Dia do Engenheiro Químico', 'Dia do Funcionário Municipal', 'Dia Internacional do Panda Vermelho', 'Dia Mundial da Limpeza'],
  '09-21': ['Dia Nacional de Conscientização da Doença de Alzheimer', 'Dia Mundial da Limpeza do Litoral', 'Dia Nacional de Luta da Pessoa com Deficiência', 'Dia Mundial da Doença de Alzheimer'],
  '09-22': ['Dia Mundial Sem Carro', 'Dia da Jornada “Na Cidade Sem Meu Carro”', 'Dia do Contador'],
  '09-23': ['Dia da Aurora', 'Dia do Técnico em Edificações', 'Dia Internacional das Línguas de Sinais', 'Dia do Técnico Industrial', 'Dia Nacional dos Profissionais de Nível Técnico', 'Dia do Soldador'],
  '09-25': ['Dia Internacional do Farmacêutico', 'Dia Nacional da Rádio', 'Dia Marítimo Mundial'],
  '09-26': ['Dia Nacional dos Surdos', 'Dia Internacional pela Eliminação Total das Armas Nucleares', 'Dia do Coala'],
  '09-27': ['Dia Nacional da Doação de Órgãos', 'Dia Nacional do Turismólogo e dos Profissionais do Turismo', 'Dia do Encanador'],
  '09-28': ['Dia Internacional do Acesso Universal à Informação', 'Dia Mundial da Luta contra à Raiva', 'Dia do Hidrógrafo'],
  '09-29': ['Dia do Anunciante', 'Dia Internacional de Conscientização sobre Perdas e Desperdício de Alimentos'],
  '09-30': ['Dia Nacional do Jornaleiro', 'Dia da Secretaria'],
  '10-01': ['Dia do Representante Comercial', 'Dia do Cão Idoso', 'Dia do Vendedor', 'Dia Internacional do Morcego', 'Outubro Rosa - Mês de conscientização sobre o câncer de mama', 'Dia do Vereador'],
  '10-03': ['Dia Mundial do Dentista'],
  '10-04': ['Dia do Cachorro', 'Dia da Adoção Animal', 'Dia da Natureza', 'Dia Nacional dos Agentes de Combate às Endemias', 'Dia Internacional do Tratador de Animais Selvagens', 'Dia do Barman', 'Dia do Cão', 'Semana Mundial do Espaço', 'Dia Nacional do Agente Comunitário de Saúde', 'Semana da Proteção à Fauna', 'Dia do Médico do Trabalho', 'Dia do Patrono da Ecologia – São Francisco'],
  '10-05': ['Dia Mundial dos Professores', 'Dia do Pet Sitter'],
  '10-06': ['Dia do Tecnólogo'],
  '10-09': ['Dia Mundial dos Correios', 'Dia Mundial da Prevenção dos Desastres Naturais'],
  '10-10': ['Dia Mundial da Saúde Mental'],
  '10-11': ['Dia Internacional da Menina', 'Dia Nacional de Prevenção da Obesidade', 'Dia da Pessoa com Deficiência Física'],
  '10-12': ['Dia Mundial para a Prevenção de Desastres Naturais', 'Dia Mundial das Aves Migratórias', 'Dia do Engenheiro Agrônomo', 'Dia do Corretor de Seguros', 'Dia dos Filhotes', 'Dia de Nossa Senhora Aparecida'],
  '10-13': ['Dia Nacional do Fisioterapeuta', 'Dia do Terapeuta Ocupacional', 'Dia do Terapeuta Ocupacional e Fisioterapeuta', 'Dia Internacional para a Redução do Risco de Desastres'],
  '10-14': ['Dia da Pecuária'],
  '10-15': ['Dia da Declaração Universal dos Direitos Animais', 'Dia do Educador Ambiental', 'Dia do Consumo Consciente', 'Dia Internacional das Mulheres Rurais'],
  '10-16': ['Dia do Chefe', 'Dia do Anestesiologista', 'Dia do Engenheiro de Alimentos'],
  '10-17': ['Dia Internacional do Bicho-Preguiça', 'Dia da Apicultura', 'Dia Internacional para a Erradicação da Pobreza'],
  '10-18': ['Dia do Securitário', 'Dia da Libertação Animal', 'Dia do Estivador'],
  '10-19': ['Dia do Profissional de Tecnologia da Informação', 'Dia do Operador de Caixa', 'Dia Mundial do Bicho-preguiça'],
  '10-20': ['Dia do Arquivista', 'Dia do Maquinista', 'Dia Mundial da Estatística'],
  '10-21': ['Dia da Consciência pelo Réptil', 'Dia Nacional de Combate à Sífilis e à Sífilis Congênita'],
  '10-22': ['Dia do Enólogo'],
  '10-24': ['Dia Mundial da Poliomielite', 'Dia das Nações Unidas', 'Semana do Desarmamento', 'Semana Mundial da Educação Midiática', 'Dia Mundial da Informação sobre o Desenvolvimento'],
  '10-25': ['Dia Nacional da Saúde Bucal', 'Dia do Lêmure', 'Dia do Cirurgião Dentista'],
  '10-27': ['Dia Nacional de Luta pelos Direitos das Pessoas com Doenças Falciformes', 'Dia Mundial do Terapeuta Ocupacional', 'Dia Mundial do Patrimônio Audiovisual', 'Dia da Conscientização pelo Gato Preto', 'Dia do Engenheiro Agrícola'],
  '10-28': ['Dia do Servidor Público'],
  '10-29': ['Dia Internacional do Gato', 'Dia Internacional do Cuidado e Apoio'],
  '10-30': ['Dia do Ginecologista', 'Dia do Comerciário', 'Dia do Balconista', 'Dia da Merendeira Escolar'],
  '10-31': ['Dia da Reforma Protestante'],
  '11-01': ['Novembro Azul – Mês de conscientização sobre a saúde do homem', 'Aniversário dos Ornitorrincos na Austrália', 'Dia de Todos os Santos', 'Dia Mundial do Veganismo', 'Semana Nacional de Prevenção do Câncer Bucal'],
  '11-02': ['Dia Internacional pelo Fim da Impunidade dos Crimes contra Jornalistas', 'Dia de Finados'],
  '11-03': ['Dia da Instituição do Direito de Voto da Mulher'],
  '11-05': ['Dia do Técnico Agrícola', 'Dia do Radioamador', 'Dia do Adestrador', 'Dia Nacional da Língua Portuguesa', 'Dia do Protético', 'Dia Mundial de Conscientização sobre Tsunamis', 'Dia Mundial Contra a Caça as Baleias', 'Dia do Técnico em Eletrônica', 'Dia da Cultura e da Ciência'],
  '11-06': ['Dia Internacional para a Prevenção da Exploração do Meio Ambiente em Guerras'],
  '11-07': ['Dia do Radialista'],
  '11-09': ['Dia do Hoteleiro', 'Dia Internacional contra o Fascismo e o Antissemitismo', 'Semana Internacional da Ciência e da Paz'],
  '11-10': ['Dia Nacional de Prevenção e Combate à Surdez', 'Dia Mundial da Ciência pela Paz e pelo Desenvolvimento'],
  '11-12': ['Dia Nacional do Inventor', 'Dia do Diretor de Escola', 'Dia Mundial da Pneumonia'],
  '11-14': ['Dia Nacional da Alfabetização', 'Dia do Vendedor Ambulante'],
  '11-15': ['Dia Internacional de Prevenção e Combate ao Crime Organizado Transnacional', 'Dia da Proclamação da República'],
  '11-16': ['Dia Internacional da Tolerância', 'Dia Nacional dos Ostomizados'],
  '11-17': ['Dia Mundial de Combate ao Câncer de Próstata', 'Dia Mundial em Memória às Vítimas do Trânsito', 'Dia Nacional de Combate à Tuberculose'],
  '11-18': ['Dia Nacional do Notário e do Registrador', 'Dia do Conselheiro Tutelar', 'Semana Mundial de Conscientização sobre a Resistência Antimicrobiana'],
  '11-19': ['Aniversário do Ministério do Meio Ambiente', 'Dia Internacional do Homem', 'Dia Mundial em Memória às Vítimas do Trânsito'],
  '11-20': ['Dia da Consciência Negra', 'Dia da Industrialização da África', 'Dia do Biomédico', 'Dia Mundial da Criança', 'Dia do Técnico em Contabilidade', 'Dia do Auditor Interno'],
  '11-21': ['Dia Mundial da Filosofia', 'Dia Mundial da Televisão'],
  '11-23': ['Dia Nacional de Enfrentamento ao Câncer Infantil', 'Dia Mundial sem Compras', 'Dia do Engenheiro Eletricista'],
  '11-24': ['Dia Mundial dos Gêmeos Siameses', 'Dia Mundial sem Consumo'],
  '11-25': ['Dia Internacional do Doador de Sangue', 'Dia Internacional pela Eliminação da Violência contra as Mulheres', 'Dia da Baiana de Acarajé'],
  '11-26': ['Dia Mundial do Transporte Sustentável'],
  '11-27': ['Dia Nacional de Luta contra o Câncer de Mama', 'Dia do Técnico em Segurança do Trabalho', 'Dia Nacional de Combate ao Câncer'],
  '11-29': ['Dia Mundial do Tamanduá', 'Dia Internacional de Solidariedade com o Povo Palestino'],
  '11-30': ['Dia do Estatuto da Terra', 'Dia em Memória das Vítimas da Guerra Química', 'Dia do Estatuto da Terra – Dia da Reforma Agrária'],
  '12-01': ['Dezembro Vermelho – Campanha Nacional de Prevenção ao HIV/AIDS e outras Infecções Sexualmente Transmissíveis', 'Dia do Numismata', 'Dia Mundial de Luta Contra a Aids', 'Dia Mundial de Conscientização e Combate à AIDS'],
  '12-02': ['Dia Pan-Americano de Saúde', 'Dia Nacional das Relações Públicas', 'Dia Internacional para a Abolição da Escravidão'],
  '12-03': ['Dia Internacional da Pessoa com Deficiência', 'Dia do Delegado de Polícia'],
  '12-04': ['Dia do Orientador Educacional', 'Dia do Trabalhador nas Minas de Carvão', 'Dia Internacional dos Bancos', 'Dia do Pedicuro'],
  '12-05': ['Dia Nacional do Médico de Família e Comunidade', 'Dia do Voluntário'],
  '12-07': ['Dia Nacional da Silvicultura', 'Dia dos Amigos do Peixe-Boi', 'Dia do Pau Brasil'],
  '12-08': ['Dia do Colunista Social', 'Dia da Justiça'],
  '12-09': ['Dia Internacional contra a Corrupção', 'Dia Internacional em Memória das Vítimas do Crime de Genocídio', 'Dia da Criança com Deficiência', 'Dia do Fonoaudiólogo'],
  '12-10': ['Dia Internacional do Direito dos Animais', 'Dia Universal dos Direitos Humanos', 'Dia dos Direitos Humanos', 'Dia da Bíblia', 'Dia do Sociólogo'],
  '12-12': ['Dia Internacional da Neutralidade', 'Dia Internacional da Cobertura Universal de Saúde'],
  '12-13': ['Dia do Engenheiro de Produção', 'Dia do Engenheiro de Pesca', 'Dia Nacional da Pessoa com Deficiência Visual', 'Dia do Pedreiro', 'Dia do Engenheiro Avaliador e Perito de Engenharia', 'Dia do Lapidador'],
  '12-14': ['Semana de Mobilização Nacional para Doação de Medula Óssea'],
  '12-18': ['Dia Internacional dos Migrantes'],
  '12-20': ['Dia do Mecânico', 'Dia Internacional da Solidariedade Humana'],
  '12-21': ['Dia Mundial da Meditação', 'Dia Mundial do Basquete'],
  '12-27': ['Dia Internacional de Preparação para Epidemias', 'Dia Internacional Brasileiro do Golfinho de Rio'],
  '12-28': ['Dia do Salva-vidas', 'Dia do Petroquímico'],
  '12-29': ['Dia Mundial da Biodiversidade'],
  '12-31': ['Réveillon'],
}
